#!/usr/bin/bash
set -euo pipefail

CURRENT_USER=$(loginctl list-sessions | awk 'NR==2 {print $3}') # We might be getting called from a udev rule
# There might not be a logged in user when udev calls this, so handle not having a user gracefully
if [[ -n "$CURRENT_USER"]]; then
    xargs ds4-led </home/$CURRENT_USER/.config/noctalia/primary-color
else
    ds4-led "#00007f"
fi
